### ISSUE TITLE
Add more troubleshooting for CentOS when installing susnstone

### ISSUE THREAD

**Issue by rzig** [OpenNebula/docs#115]
As I was installing sunstone on CentOS, I was not able to access the web ui even though `netstat` showed the port was open and the logs showed success. As it turned out, I had to run `iptables -I INPUT 5 -p tcp -m state --state NEW -m tcp --dport 9869 -j ACCEPT` and `service iptables save` to get access. Would you like me to open up a PR and get this in the docs?

**Comment by tinova** [comment]
Sorry for the delay in answering, we are slowly catching up. Yes, please, we'd like a PR to cover this potential issue.
