### ISSUE TITLE
help me!   rror parsing host information: syntax error, unexpected 

### ISSUE THREAD

**Issue by sakufo** [OpenNebula/docs#147]
Wed Nov 15 11:15:38 2017 [Z0][ONE][E]: Error parsing host information: syntax error, unexpected VARIABLE, expecting EQUAL or EQUAL_EMPTY at line 1, columns 7:11. Monitoring information: 
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

version:5.2.0

**Comment by tinova** [comment]
Please use the OpenNebula/one project for software related issues
