### ISSUE TITLE
Hotfix release

### ISSUE THREAD

**Issue by hydro-b** [OpenNebula/docs#148]
The what_is_hotfix.html page, currently: http://docs.opennebula.org/5.4/intro_release_notes/release_notes_hotfix/what_is_hotfix.html

has a reference to "templates to create packages for the different supported platforms." with a link to "https://github.com/OpenNebula/one/tree/master/share/pkgs". I don't think that is the page you want to link to, but _this_ is: https://github.com/OpenNebula/packages.

"Edit on github" does not work for mentioned page. I did a "git clone" of the docs repo but cannot find the page, so openening this issue instead.

**Comment by jmelis** [comment]
Hi, I have fixed it, thanks for the heads up :)

Regarding "Edit on github" that has been broken for a long time, it always opens "master" branch regardless of what version you are currently using...
