### ISSUE TITLE
Ceph Datastore

### ISSUE THREAD

**Issue by sakufo** [OpenNebula/docs#162]
What is the content of this option?
BRIDGE_LIST	List of storage bridges to access the Ceph cluster

The ceph datastore I created is wrong to understand

Thu Dec 14 14:48:09 2017 [Z0][ImM][I]: Command execution fail: /var/lib/one/remotes/datastore/ceph/monitor PERTX0RSSVZFUl9BQ1RJT05fREFUQT48REFUQVNUT1JFPjxJRD4xMzE8L0lEPjxVSUQ+NjwvVUlEPjxHSUQ+MDwvR0lEPjxVTkFNRT54ZHpodTwvVU5BTUU+PEdOQU1FPm9uZWFkbWluPC9HTkFNRT48TkFNRT5jZXBoLW9uZTwvTkFNRT48UEVSTUlTU0lPTlM+PE9XTkVSX1U+MTwvT1dORVJfVT48T1dORVJfTT4xPC9PV05FUl9NPjxPV05FUl9BPjA8L09XTkVSX0E+PEdST1VQX1U+MTwvR1JPVVBfVT48R1JPVVBfTT4wPC9HUk9VUF9NPjxHUk9VUF9BPjA8L0dST1VQX0E+PE9USEVSX1U+MDwvT1RIRVJfVT48T1RIRVJfTT4wPC9PVEhFUl9NPjxPVEhFUl9BPjA8L09USEVSX0E+PC9QRVJNSVNTSU9OUz48RFNfTUFEPjwhW0NEQVRBW2NlcGhdXT48L0RTX01BRD48VE1fTUFEPjwhW0NEQVRBW2NlcGhdXT48L1RNX01BRD48QkFTRV9QQVRIPjwhW0NEQVRBWy9kYXRhL29wZW5uZWJ1bGEvZGF0YXpvbmUvMTMxXV0+PC9CQVNFX1BBVEg+PFRZUEU+MDwvVFlQRT48RElTS19UWVBFPjM8L0RJU0tfVFlQRT48U1RBVEU+MDwvU1RBVEU+PENMVVNURVJTPjxJRD4wPC9JRD48L0NMVVNURVJTPjxUT1RBTF9NQj4wPC9UT1RBTF9NQj48RlJFRV9NQj4wPC9GUkVFX01CPjxVU0VEX01CPjA8L1VTRURfTUI+PElNQUdFUz48L0lNQUdFUz48VEVNUExBVEU+PEFMTE9XX09SUEhBTlM+PCFbQ0RBVEFbWUVTXV0+PC9BTExPV19PUlBIQU5TPjxCUklER0VfTElTVD48IVtDREFUQVsxOTIuMTY4LjMuMTQgMTkyLjE2OC4zLjE1IDE5Mi4xNjguOTkuMTZdXT48L0JSSURHRV9MSVNUPjxDRVBIX0NPTkY+PCFbQ0RBVEFbL2V0Yy9jZXBoL2NlcGguY29uZl1dPjwvQ0VQSF9DT05GPjxDRVBIX0hPU1Q+PCFbQ0RBVEFbMTkyLjE2OC4zLjE0IDE5Mi4xNjguMy4xNSAxOTIuMTY4Ljk5LjE2XV0+PC9DRVBIX0hPU1Q+PENFUEhfU0VDUkVUPjwhW0NEQVRBW0FRRFd5UWxhWjArVUJoQUFzRTFySVlHcFJ2SzdDYXVvaDNJa0xRPT1dXT48L0NFUEhfU0VDUkVUPjxDRVBIX1VTRVI+PCFbQ0RBVEFbYWRtaW5dXT48L0NFUEhfVVNFUj48Q0xPTkVfVEFSR0VUPjwhW0NEQVRBW1NFTEZdXT48L0NMT05FX1RBUkdFVD48RElTS19UWVBFPjwhW0NEQVRBW1JCRF1dPjwvRElTS19UWVBFPjxEUklWRVI+PCFbQ0RBVEFbcmF3XV0+PC9EUklWRVI+PERTX01BRD48IVtDREFUQVtjZXBoXV0+PC9EU19NQUQ+PExOX1RBUkdFVD48IVtDREFUQVtOT05FXV0+PC9MTl9UQVJHRVQ+PFBPT0xfTkFNRT48IVtDREFUQVtvbmVdXT48L1BPT0xfTkFNRT48UkJEX0ZPUk1BVD48IVtDREFUQVsxXV0+PC9SQkRfRk9STUFUPjxSRVNUUklDVEVEX0RJUlM+PCFbQ0RBVEFbL11dPjwvUkVTVFJJQ1RFRF9ESVJTPjxTQUZFX0RJUlM+PCFbQ0RBVEFbL3Zhci90bXBdXT48L1NBRkVfRElSUz48VE1fTUFEPjwhW0NEQVRBW2NlcGhdXT48L1RNX01BRD48VFlQRT48IVtDREFUQVtJTUFHRV9EU11dPjwvVFlQRT48L1RFTVBMQVRFPjwvREFUQVNUT1JFPjwvRFNfRFJJVkVSX0FDVElPTl9EQVRBPg== 131
Thu Dec 14 14:48:09 2017 [Z0][ImM][I]: ExitCode: 1
Thu Dec 14 14:48:09 2017 [Z0][ImM][E]: Error monitoring datastore 131: LQ==. Decoded info: -

**Comment by rsmontero** [comment]
Content of BRIDGE_LIST is the list of Ceph clients used to monitor and/or register images. This is stated in the documentation

```
Pick a set of client nodes of the cluster to act as storage bridges. These nodes will be used to import images into the Ceph Cluster from OpenNebula. These nodes must have qemu-img command installed.
```

Please use the opennebula forums for technical assistance. Issues in this repository are for improving the documentation

**Comment by sakufo** [comment]
@rsmontero
Thank you for your help, I will try again.
I love you! :)
