### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Pablohn26** [OpenNebula/docs#73]
It seems Github-sphinx integration is a little bit broken.

If you go [here](http://docs.opennebula.org/4.12/advanced_administration/data_center_federation/federationmng.html) and click on "Edit in Github", you get [this](https://github.com/OpenNebula/docs/blob/master/source/advanced_administration/data_center_federation/federationmng.rst) broken link rather than [this](https://github.com/OpenNebula/docs/blob/master/source/advanced_components/data_center_federation/federationmng.rst). It seems the only change is advanced_administration by advanced_components in the URL. Not sure if it is a bug but worths mention it.

**Comment by jmelis** [comment]
Hey @Pablohn26 thanks for reporting this. It's a problem indeed, basically the "Edit in Github" button only works for the latest branch: it always points to master and not to the branch you came from, which in your case should be "4.12".

Anyways, I think we are not going to fix it, as we recommend users to upgrade to the latest release. I took a look a while back and it requires some time, so apologies for closing this without fixing :)

May I suggest you guys upgrade to 5.2??
