### ISSUE TITLE
Want to integrate ceph 3 node cluster with opennebula 5.2

### ISSUE THREAD

**Issue by subhashchand** [OpenNebula/docs#81]
We had followed this document(https://opennebula.org/installation-of-ha-opennebula-on-centos-7-with-ceph-as-a-datastore-and-ipoib-as-backend-network/comment-page-1/#comment-145477) for setup CEPH cluster integration with OpenNebula 5.2. but we faced some issues on that, after creating CEPH cluster when try to integrating with opennebula frontend node then its not getting up and not showing disk uasble space.

[oneadmin@node1 ~]$ cat cephds.conf
NAME = “cephds”
DS_MAD = ceph
TM_MAD = ceph
DISK_TYPE = RBD
POOL_NAME = data
CEPH_HOST = storage1-storage2-storage3
CEPH_USER = oneadmin
CEPH_SECRET = “AQCU1GxYHmbkBxAA6TlD6q+PyMTL+/a+AB+2bg==2dsf”
BRIDGE_LIST = storage1

[cephuser@storage1 ~]$ ceph -s
cluster dd8ea244-d2e4-4948-b3b8-ec2ddedeff80
health HEALTH_OK
monmap e1: 3 mons at {storage1=XX:XX:XX:137:6789/0,storage2=XX.XX.XX.138:6789/0,storage3=XX.XX.XX.139:6789/0}
election epoch 70, quorum 0,1,2 storage1,storage2,storage3
osdmap e204: 3 osds: 3 up, 3 in
flags sortbitwise,require_jewel_osds
pgmap v312560: 2112 pgs, 3 pools, 14641 kB data, 24 objects
19914 MB used, 11104 GB / 11123 GB avail
2112 active+clean

Please suggest us.

**Comment by subhashchand** [comment]
![datastore](https://cloud.githubusercontent.com/assets/10760179/21849783/86ce12be-d82d-11e6-8c39-0b663066c428.PNG)

**Comment by subhashchand** [comment]
Some more updates on CEPH Cluster:  
I have setup 3 nodes CEPH storage cluster and all are working fine and data replicated on each node after that we want to integrate with OpenNebula 5.2 we have setup as below setting as shared storage but no getting up as shared storage on opennebula frontend. 

![image](https://cloud.githubusercontent.com/assets/10760179/22009572/1fbe4860-dcaa-11e6-8306-114a2c1cb36b.png)

**Comment by rsmontero** [comment]
Please use the opennebula forum http://forum.opennebula.org/
